server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_service?serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: blogservice # 博客服务的服务名称
  cloud:
    nacos:
     server-addr: localhost:8848

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


ribbon:
  eager-load:
    enabled: true
    clients: userservice # 饥饿加载