server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/users/** # 路径断言，判断路径是否是以/users开头，如果是则符合
        - id: blog-service
          uri: lb://blogservice
          predicates:
            - Path=/articles/**